In [28]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [29]:
df=pd.read_excel("Global Landslide Data.xlsx",index_col='id')

In [30]:
df.columns

Index(['date', 'time', 'country', 'nearest_places', 'hazard_type',
       'landslide_type', 'trigger', 'storm_name', 'fatalities', 'injuries',
       'source_name', 'source_link', 'comments', 'location_description',
       'location_accuracy', 'landslide_size', 'photos_link', 'cat_src',
       'cat_id', 'countryname', 'near', 'distance', 'adminname1', 'adminname2',
       'population', 'countrycode', 'continentcode', 'key', 'version',
       'tstamp', 'changeset_id', 'latitude', 'longitude', 'geolocation'],
      dtype='object')

In [31]:
df.shape

(1693, 34)

In [32]:
df.head()

,date,time,country,nearest_places,hazard_type,landslide_type,trigger,storm_name,fatalities,injuries,...,population,countrycode,continentcode,key,version,tstamp,changeset_id,latitude,longitude,geolocation
id,,,,,,,,,,,,,,,,,,,,,
7494,2015-09-25,NaN,NaN,"Barrio Tournon, San Jose",landslide,Landslide,Rain,NaN,0.0,0.0,...,335007.0,CR,NaN,D56hGDdNGk,2,Wed Feb 10 2016 16:47:33 GMT+0000 (UTC),3456375012,9.9402,-84.0771,"(9.9402, -84.0771)"
249,2007-09-09,NaN,Costa Rica,Heredia,landslide,Landslide,Rain,NaN,NaN,NaN,...,21947.0,CR,NaN,D58b6sgBW,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),1,10.0000,-84.1167,"(10.0, -84.1167)"
250,2007-09-09,NaN,Dominica,"entire island, Roseau closed",landslide,Landslide,Rain,Tropical Wave,NaN,NaN,...,16571.0,DM,NaN,SGXR7ZFcU,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),1,15.3055,-61.3642,"(15.3055, -61.3642)"
7541,2016-03-02,08:00:00,NaN,south bound travel lane of Interstate 91 in Wi...,landslide,Rock_Fall,Unknown,NaN,0.0,0.0,...,2066.0,US,NaN,h9c5OODjSn,2,Sun Mar 06 2016 22:23:45 GMT+0000 (UTC),4281763033,43.4771,-72.4066,"(43.4771, -72.4066)"
7533,2016-02-27,12:15:00,NaN,"Simmons Avenue, Bramwell",landslide,Rock_Fall,Unknown,NaN,0.0,0.0,...,2184.0,US,NaN,s9KadynMD8,1,Tue Mar 01 2016 00:01:15 GMT+0000 (UTC),580117165,37.3287,-81.3134,"(37.3287, -81.3134)"

In [33]:
# sns.pairplot(df,hue="landslide_type")
# plt.show()

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1693 entries, 7494 to 7042
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  1690 non-null   datetime64[ns]
 1   time                  629 non-null    object
 2   country               1286 non-null   object
 3   nearest_places        1683 non-null   object
 4   hazard_type           1693 non-null   object
 5   landslide_type        1692 non-null   object
 6   trigger               1691 non-null   object
 7   storm_name            134 non-null    object
 8   fatalities            1446 non-null   float64
 9   injuries              515 non-null    float64
 10  source_name           872 non-null    object
 11  source_link           1593 non-null   object
 12  comments              1652 non-null   object
 13  location_description  552 non-null    object
 14  location_accuracy     1693 non-null   object
 15  landslide_size        1692 non-null   object
 16  photos_link           203 non-null    object
 17  cat_src               1692 non-null   object
 18  cat_id                1693 non-null   object
 19  countryname           1693 non-null   object
 20  near                  1692 non-null   object
 21  distance              1692 non-null   float64
 22  adminname1            1692 non-null   object
 23  adminname2            1259 non-null   object
 24  population            1692 non-null   float64
 25  countrycode           1693 non-null   object
 26  continentcode         165 non-null    object
 27  key                   1693 non-null   object
 28  version               1693 non-null   int64
 29  tstamp                1692 non-null   object
 30  changeset_id          1693 non-null   object
 31  latitude              1693 non-null   float64
 32  longitude             1693 non-null   float64
 33  geolocation           1693 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(1), object(26)
memory usage: 462.9+ KB

In [35]:
objList = df.select_dtypes(include = "object").columns
print (objList)

Index(['time', 'country', 'nearest_places', 'hazard_type', 'landslide_type',
       'trigger', 'storm_name', 'source_name', 'source_link', 'comments',
       'location_description', 'location_accuracy', 'landslide_size',
       'photos_link', 'cat_src', 'cat_id', 'countryname', 'near', 'adminname1',
       'adminname2', 'countrycode', 'continentcode', 'key', 'tstamp',
       'changeset_id', 'geolocation'],
      dtype='object')

In [36]:
df.isnull().sum()

date                       3
time                    1064
country                  407
nearest_places            10
hazard_type                0
landslide_type             1
trigger                    2
storm_name              1559
fatalities               247
injuries                1178
source_name              821
source_link              100
comments                  41
location_description    1141
location_accuracy          0
landslide_size             1
photos_link             1490
cat_src                    1
cat_id                     0
countryname                0
near                       1
distance                   1
adminname1                 1
adminname2               434
population                 1
countrycode                0
continentcode           1528
key                        0
version                    0
tstamp                     1
changeset_id               0
latitude                   0
longitude                  0
geolocation                0
dtype: int64

In [37]:
df=df.drop(['time','storm_name','injuries','source_name','key','source_link','location_description','photos_link','adminname1','adminname2','continentcode','country','hazard_type','comments','fatalities','nearest_places','changeset_id','cat_src','cat_id'],1)

In [38]:
df=df.dropna(how='any',axis=0)

In [39]:
df.isnull().sum()

date                 0
landslide_type       0
trigger              0
location_accuracy    0
landslide_size       0
countryname          0
near                 0
distance             0
population           0
countrycode          0
version              0
tstamp               0
latitude             0
longitude            0
geolocation          0
dtype: int64

In [40]:
df.shape

(1686, 15)

In [41]:
df.head()

,date,landslide_type,trigger,location_accuracy,landslide_size,countryname,near,distance,population,countrycode,version,tstamp,latitude,longitude,geolocation
id,,,,,,,,,,,,,,,
7494,2015-09-25,Landslide,Rain,Known_within_1km,Small,Costa Rica,San JosÃƒÂ©,1.16705,335007.0,CR,2,Wed Feb 10 2016 16:47:33 GMT+0000 (UTC),9.9402,-84.0771,"(9.9402, -84.0771)"
249,2007-09-09,Landslide,Rain,Known_within_5_km,Medium,Costa Rica,Heredia,0.26208,21947.0,CR,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),10.0000,-84.1167,"(10.0, -84.1167)"
250,2007-09-09,Landslide,Rain,Known_within_25_km,Medium,Dominica,Roseau,2.59849,16571.0,DM,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),15.3055,-61.3642,"(15.3055, -61.3642)"
7541,2016-03-02,Rock_Fall,Unknown,Known_within_10km,Small,United States,Windsor,1.78429,2066.0,US,2,Sun Mar 06 2016 22:23:45 GMT+0000 (UTC),43.4771,-72.4066,"(43.4771, -72.4066)"
7533,2016-02-27,Rock_Fall,Unknown,Known_within_1km,Small,United States,Bluewell,5.07093,2184.0,US,1,Tue Mar 01 2016 00:01:15 GMT+0000 (UTC),37.3287,-81.3134,"(37.3287, -81.3134)"

In [42]:
df.columns

Index(['date', 'landslide_type', 'trigger', 'location_accuracy',
       'landslide_size', 'countryname', 'near', 'distance', 'population',
       'countrycode', 'version', 'tstamp', 'latitude', 'longitude',
       'geolocation'],
      dtype='object')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1686 entries, 7494 to 34
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1686 non-null   datetime64[ns]
 1   landslide_type     1686 non-null   object
 2   trigger            1686 non-null   object
 3   location_accuracy  1686 non-null   object
 4   landslide_size     1686 non-null   object
 5   countryname        1686 non-null   object
 6   near               1686 non-null   object
 7   distance           1686 non-null   float64
 8   population         1686 non-null   float64
 9   countrycode        1686 non-null   object
 10  version            1686 non-null   int64
 11  tstamp             1686 non-null   object
 12  latitude           1686 non-null   float64
 13  longitude          1686 non-null   float64
 14  geolocation        1686 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(9)
memory usage: 210.8+ KB

In [44]:
df['landslide_type'].unique()

array(['Landslide', 'Rock_Fall', 'Mudslide', 'Debris_Flow',
       'Riverbank_Collapse', 'Other', 'Complex', 'Creep', 'Rockslide',
       'mudslide', 'landslide', 'Unknown', 'Snow_Avalanche', 'Rockfall',
       'Lahar'], dtype=object)

In [45]:
df['landslide_type'].replace(to_replace=['Landslide','Rock_Fall','Mudslide','Debris_Flow','Riverbank_Collapse','Other','Complex','Creep','Rockslide','mudslide','landslide','Unknown','Snow_Avalanche','Rockfall','Lahar'], value=[1,2,3,4,5,6,7,8,9,3,1,12,13,2,15], inplace=True)

In [46]:
df['trigger'].unique()

array(['Rain', 'Unknown', 'Continuous_rain', 'Downpour', 'Freeze_thaw',
       'Tropical_Cyclone', 'Flooding', 'Mining_digging', 'downpour',
       'Construction', 'Volcano', 'Snowfall_snowmelt',
       'No_Apparent_trigger', 'Earthquake', 'unknown', 'Continuous_Rain',
       'Other', 'Dam_Embankment_Collapse'], dtype=object)

In [47]:
df['trigger'].replace(to_replace=['Rain', 'Unknown', 'Continuous_rain', 'Downpour', 'Freeze_thaw',
       'Tropical_Cyclone', 'Flooding', 'Mining_digging', 'downpour',
       'Construction', 'Volcano', 'Snowfall_snowmelt',
       'No_Apparent_trigger', 'Earthquake', 'unknown', 'Continuous_Rain',
       'Other', 'Dam_Embankment_Collapse'],value=[1,2,3,4,5,6,7,8,4,10,11,12,13,14,2,3,3,18],inplace=True)

In [48]:
df['location_accuracy'].unique()

array(['Known_within_1km', 'Known_within_5_km', 'Known_within_25_km',
       'Known_within_10km', 'Exact_location', 'Known_within_5km',
       'Known_within_1_km', 'Known_within_15km', 'Known_within_25km',
       'Known_within_10_km', 'Unknown', 'Known_within_50km',
       'Exact_Location', 'Known_within_50_km', 'Known_within_2km',
       'Known_within_15_km', 'Known_within_20_km'], dtype=object)

In [49]:
df['location_accuracy'].replace(to_replace=['Exact_location','Exact_Location','Known_within_1km','Known_within_1_km','Known_within_2km','Known_within_5km','Known_within_5_km','Known_within_10km','Known_within_10_km','Known_within_15km','Known_within_15_km','Known_within_20_km','Known_within_25_km','Known_within_25km','Known_within_50km', 'Known_within_50_km','Unknown'],value=[0,0,1,1,2,5,5,10,10,15,15,20,25,25,50,50,50],inplace=True)

In [50]:
df.head()

,date,landslide_type,trigger,location_accuracy,landslide_size,countryname,near,distance,population,countrycode,version,tstamp,latitude,longitude,geolocation
id,,,,,,,,,,,,,,,
7494,2015-09-25,1,1,1,Small,Costa Rica,San JosÃƒÂ©,1.16705,335007.0,CR,2,Wed Feb 10 2016 16:47:33 GMT+0000 (UTC),9.9402,-84.0771,"(9.9402, -84.0771)"
249,2007-09-09,1,1,5,Medium,Costa Rica,Heredia,0.26208,21947.0,CR,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),10.0000,-84.1167,"(10.0, -84.1167)"
250,2007-09-09,1,1,25,Medium,Dominica,Roseau,2.59849,16571.0,DM,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),15.3055,-61.3642,"(15.3055, -61.3642)"
7541,2016-03-02,2,2,10,Small,United States,Windsor,1.78429,2066.0,US,2,Sun Mar 06 2016 22:23:45 GMT+0000 (UTC),43.4771,-72.4066,"(43.4771, -72.4066)"
7533,2016-02-27,2,2,1,Small,United States,Bluewell,5.07093,2184.0,US,1,Tue Mar 01 2016 00:01:15 GMT+0000 (UTC),37.3287,-81.3134,"(37.3287, -81.3134)"

In [51]:
df['landslide_size'].unique()

array(['Small', 'Medium', 'Large', 'small', 'Very_large', 'medium',
       'large'], dtype=object)

In [52]:
df['landslide_size'].replace(to_replace=['Small', 'Medium', 'Large', 'small', 'Very_large', 'medium','large'],value=[0,1,2,0,3,1,2],inplace=True)

In [53]:
df.head()

,date,landslide_type,trigger,location_accuracy,landslide_size,countryname,near,distance,population,countrycode,version,tstamp,latitude,longitude,geolocation
id,,,,,,,,,,,,,,,
7494,2015-09-25,1,1,1,0,Costa Rica,San JosÃƒÂ©,1.16705,335007.0,CR,2,Wed Feb 10 2016 16:47:33 GMT+0000 (UTC),9.9402,-84.0771,"(9.9402, -84.0771)"
249,2007-09-09,1,1,5,1,Costa Rica,Heredia,0.26208,21947.0,CR,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),10.0000,-84.1167,"(10.0, -84.1167)"
250,2007-09-09,1,1,25,1,Dominica,Roseau,2.59849,16571.0,DM,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),15.3055,-61.3642,"(15.3055, -61.3642)"
7541,2016-03-02,2,2,10,0,United States,Windsor,1.78429,2066.0,US,2,Sun Mar 06 2016 22:23:45 GMT+0000 (UTC),43.4771,-72.4066,"(43.4771, -72.4066)"
7533,2016-02-27,2,2,1,0,United States,Bluewell,5.07093,2184.0,US,1,Tue Mar 01 2016 00:01:15 GMT+0000 (UTC),37.3287,-81.3134,"(37.3287, -81.3134)"

In [54]:
df=df.drop(['countryname','near','countrycode','tstamp','geolocation'],1)

In [55]:
df.head()

,date,landslide_type,trigger,location_accuracy,landslide_size,distance,population,version,latitude,longitude
id,,,,,,,,,,
7494,2015-09-25,1,1,1,0,1.16705,335007.0,2,9.9402,-84.0771
249,2007-09-09,1,1,5,1,0.26208,21947.0,1,10.0000,-84.1167
250,2007-09-09,1,1,25,1,2.59849,16571.0,1,15.3055,-61.3642
7541,2016-03-02,2,2,10,0,1.78429,2066.0,2,43.4771,-72.4066
7533,2016-02-27,2,2,1,0,5.07093,2184.0,1,37.3287,-81.3134

In [56]:
x=df
y=df['landslide_type']

In [57]:
x.shape

(1686, 10)

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
                                                    random_state=1)

In [59]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(X_test.shape)

(1348, 10)
(1348,)
(338, 10)
(338, 10)